apiVersion: v2
name: mediamicroservices-aegis
description: DeathStarBench MediaMicroservices (C++) wrapper for aegis.
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: media-microservices
    version: 0.1.0
    repository: ""
